# Auditoria da YouTube API - tudo num arquivo so.
#
# GERADO por gerar_ps1.py. Nao edite este arquivo: ele carrega copia de
# auditoria_demo.py dentro de si, e copia mantida a mao e copia que se afasta
# da original sem avisar. Mude o .py e rode o gerador.
#
# Uso:  botao direito -> Executar com o PowerShell
#   ou: Set-ExecutionPolicy -Scope Process Bypass -Force; & "$env:USERPROFILE\Downloads\auditoria.ps1"

$ErrorActionPreference = "Stop"
$pasta = Join-Path $env:USERPROFILE "Downloads"
Set-Location $pasta

Write-Host ""
Write-Host "=============================================================" -ForegroundColor Cyan
Write-Host "  Auditoria da YouTube API - Receita Video Pipeline" -ForegroundColor Cyan
Write-Host "=============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Pasta de trabalho: $pasta"
Write-Host ""

# ---------------------------------------------------------- 1. client secret
# So confere que EXISTE algum. QUAL usar e decisao do programa, que le o JSON:
# a pasta costuma ter o client secret de mais de um projeto, e escolher pelo
# nome escolhe por acaso.
$n = @(Get-ChildItem -Path $pasta -Filter "client_secret*.json" -ErrorAction SilentlyContinue).Count
if ($n -eq 0) {
    Write-Host "  X  Nao achei nenhum client_secret*.json em $pasta" -ForegroundColor Red
    Write-Host ""
    Write-Host "     Baixe o JSON do Google Cloud (tela Clientes -> baixar JSON)"
    Write-Host "     e deixe ele na pasta Downloads. Depois rode este arquivo de novo."
    Write-Host ""
    Read-Host "Enter para fechar" ; exit 1
}
Write-Host "  ok  client secret presente ($n arquivo(s))" -ForegroundColor Green

# ------------------------------------------------------------------ 2. Python
function Achar-Python {
    foreach ($c in @("python", "py")) {
        $g = Get-Command $c -ErrorAction SilentlyContinue
        if ($g) {
            # `python` no Windows costuma ser um atalho da Microsoft Store que
            # nao executa nada e so abre a loja. Uma chamada real desmascara.
            try { & $c --version *> $null; if ($LASTEXITCODE -eq 0) { return $c } } catch { }
        }
    }
    $p = Get-ChildItem "$env:LOCALAPPDATA\Programs\Python\Python3*\python.exe" -ErrorAction SilentlyContinue |
         Sort-Object FullName -Descending | Select-Object -First 1
    if ($p) { return $p.FullName }
    return $null
}

$py = Achar-Python
if (-not $py) {
    Write-Host "  ..  Python nao encontrado. Instalando..." -ForegroundColor Yellow
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        winget install -e --id Python.Python.3.12 --scope user --silent `
              --accept-source-agreements --accept-package-agreements
        $py = Achar-Python
    }
}
if (-not $py) {
    Write-Host "  X  Nao consegui instalar o Python sozinho." -ForegroundColor Red
    Write-Host "     Abrindo a pagina. MARQUE 'Add python.exe to PATH' na primeira tela."
    Start-Process "https://www.python.org/downloads/"
    Read-Host "Enter para fechar" ; exit 1
}
Write-Host "  ok  python: $py" -ForegroundColor Green

# --------------------------------------------------------------- 3. bibliotecas
Write-Host "  ..  conferindo bibliotecas (demora so na primeira vez)"
& $py -m pip install --quiet --upgrade --disable-pip-version-check `
      google-auth-oauthlib google-api-python-client
Write-Host "  ok  bibliotecas" -ForegroundColor Green

# ------------------------------------------- 4. grava o programa e o video
$alvo = Join-Path $pasta "auditoria_demo.py"
$programa = @'
#!/usr/bin/env python3
"""Demonstracao do fluxo OAuth, para gravar o video da auditoria da YouTube API.

Existe porque a auditoria exige um video mostrando a tela de consentimento DO
NOSSO app e o que ele faz com o acesso — e a maquina publica hoje pela
Upload-Post, sem OAuth proprio. Nao havia o que gravar.

E um arquivo so, de proposito: quem vai gravar nao precisa instalar o projeto
inteiro, so o Python e duas bibliotecas. Toda a saida sai em INGLES porque o
terminal aparece no video e quem le e o revisor do Google.

Uso normal: duplo clique em 1-ENSAIO.bat ou 2-GRAVAR.bat.

Pela linha de comando:
    python auditoria_demo.py [client_secret.json] [video.mp4]

Os dois argumentos sao OPCIONAIS. Sem eles o script procura sozinho, na
propria pasta, um `client_secret*.json` e o `demo_upload.mp4`. Isso existe
porque digitar `client_secret_777159180424-a1b2c3.apps.googleusercontent.com
.json` sem errar, num Prompt de Comando, e um obstaculo real para quem so
quer gravar um video de 90 segundos.

Sem video ele so autentica e mostra o canal — o ensaio. Com video, faz o
upload de verdade, que e o trecho final que o revisor precisa ver.
"""
import glob
import json
import os
import sys

ESCOPOS = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube",
    "https://www.googleapis.com/auth/yt-analytics.readonly",
]


def linha(t=""):
    print(t, flush=True)


def autenticar(segredo):
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow

    token = os.path.join(os.path.dirname(os.path.abspath(segredo)), "token.json")
    cred = None
    if os.path.exists(token):
        cred = Credentials.from_authorized_user_file(token, ESCOPOS)
    if cred and cred.expired and cred.refresh_token:
        cred.refresh(Request())
    if not cred or not cred.valid:
        linha("No stored credentials. Starting OAuth consent flow...")
        linha("A browser window will open. Review the requested permissions.")
        linha()
        cred = InstalledAppFlow.from_client_secrets_file(
            segredo, ESCOPOS).run_local_server(port=0)
        # O token fica ao lado do segredo, nao no diretorio corrente: quem grava
        # o video roda de qualquer pasta, e um token perdido faz o ensaio
        # seguinte reabrir o consentimento sem aviso.
        with open(token, "w", encoding="utf-8") as f:
            f.write(cred.to_json())
        linha(f"Consent granted. Credentials stored in {token}")
    else:
        linha("Using stored credentials.")
    return cred


def mostrar_canal(api):
    r = api.channels().list(part="snippet,statistics", mine=True).execute()
    itens = r.get("items") or []
    if not itens:
        sys.exit("ERROR: these credentials do not control any YouTube channel.")
    c = itens[0]
    linha()
    linha("AUTHENTICATED CHANNEL (owned by the person granting consent)")
    linha(f"  title       {c['snippet']['title']}")
    linha(f"  channel id  {c['id']}")
    linha(f"  subscribers {c['statistics'].get('subscriberCount', 'hidden')}")
    linha(f"  videos      {c['statistics'].get('videoCount', '0')}")
    linha()


def enviar(api, caminho):
    from googleapiclient.http import MediaFileUpload

    corpo = {
        "snippet": {
            "title": "OAuth demonstration upload",
            "description": ("Test upload recorded for the YouTube API Services "
                            "audit submission. Uploaded by the channel owner to "
                            "the channel owner's own channel."),
            "categoryId": "27",
        },
        # Privado de proposito. Nao contraria a regra de publicar sempre em
        # publico: isto nao e publicacao, e a demonstracao — e enquanto o
        # projeto nao esta auditado o proprio YouTube forca privado de todo
        # jeito. O video mostra exatamente a limitacao que a auditoria remove.
        "status": {
            "privacyStatus": "private",
            "selfDeclaredMadeForKids": False,
            "containsSyntheticMedia": True,
        },
    }
    linha(f"Uploading {caminho} via youtube.videos.insert ...")
    req = api.videos().insert(part="snippet,status", body=corpo,
                              media_body=MediaFileUpload(caminho,
                                                         chunksize=-1,
                                                         resumable=True))
    resp = req.execute()
    vid = resp["id"]
    linha()
    linha("UPLOAD COMPLETE")
    linha(f"  video id  {vid}")
    linha(f"  url       https://www.youtube.com/watch?v={vid}")
    linha(f"  privacy   {resp['status']['privacyStatus']}")
    linha()
    # O privado nao e falha nossa e o revisor precisa ler isto na tela: e a
    # restricao que a auditoria remove, demonstrada ao vivo.
    linha("Note: the upload is forced to private because this API project has")
    linha("not been audited yet. Removing that restriction is the purpose of")
    linha("this audit request.")
    linha()
    linha("Open YouTube Studio to confirm the video is listed on the channel.")


def achar(padrao, dado):
    """Procura o arquivo na pasta do script, nao no diretorio corrente.

    Um duplo clique no .bat pode abrir o terminal em qualquer lugar; a unica
    pasta de que se tem certeza e a do proprio script.
    """
    aqui = os.path.dirname(os.path.abspath(__file__))
    achados = sorted(glob.glob(os.path.join(aqui, padrao)))
    if not achados:
        sys.exit(f"ERROR: no {dado} found.\n"
                 f"Expected a file matching '{padrao}' in:\n  {aqui}")
    if len(achados) > 1:
        linha(f"Note: {len(achados)} candidates found, using the first:")
        for a in achados:
            linha(f"  {os.path.basename(a)}")
    return achados[0]


def achar_segredo():
    """Escolhe o client secret pelo CONTEUDO, nunca pela ordem do nome.

    A pasta Downloads costuma ter mais de um: cada projeto do Google Cloud
    baixa o seu, e o nome comeca com o numero do projeto. Ordenar por nome
    escolhe por acaso — foi o que aconteceu, e o cliente errado so falhou
    depois, ja com o Python instalado e as bibliotecas baixadas.

    Cliente de app instalado tem a chave "installed" no JSON; cliente Web tem
    "web". Filtrar por isso deixa passar so o que pode funcionar, e entre os
    que sobram vale o mais recente.
    """
    aqui = os.path.dirname(os.path.abspath(__file__))
    cands = sorted(glob.glob(os.path.join(aqui, "client_secret*.json")))
    if not cands:
        sys.exit("ERROR: no client secret found.\n"
                 f"Expected a file matching 'client_secret*.json' in:\n  {aqui}")
    bons = []
    for c in cands:
        try:
            if "installed" in json.load(open(c, encoding="utf-8")):
                bons.append(c)
        except (OSError, ValueError):
            pass
    if not bons:
        linha(f"Found {len(cands)} client secret file(s), none of them a Desktop app client:")
        for c in cands:
            linha(f"  {os.path.basename(c)}")
        sys.exit("\nERROR: in Google Cloud, create the OAuth client with "
                 "application type 'Desktop app' and download that JSON.")
    bons.sort(key=os.path.getmtime, reverse=True)
    if len(cands) > 1:
        linha(f"{len(cands)} client secret files present; using the most recent "
              f"Desktop app client:")
        linha(f"  {os.path.basename(bons[0])}")
    return bons[0]


def main():
    args = sys.argv[1:]
    segredo = args[0] if args else achar_segredo()
    if not os.path.exists(segredo):
        sys.exit(f"ERROR: client secret not found at {segredo}")
    # Confere que e mesmo um cliente de app instalado. Cliente "Web" tambem
    # baixa um JSON parecido e so falha depois, no meio do consentimento —
    # tarde demais para quem ja apertou o gravador.
    dados = json.load(open(segredo, encoding="utf-8"))
    if "installed" not in dados:
        sys.exit("ERROR: this client secret is not a Desktop app client.\n"
                 "In Google Cloud, create the OAuth client with application "
                 "type 'Desktop app' and download that JSON instead.")

    from googleapiclient.discovery import build

    linha("=" * 62)
    linha("Receita Video Pipeline - YouTube API access demonstration")
    linha("=" * 62)
    linha()
    cred = autenticar(segredo)
    api = build("youtube", "v3", credentials=cred)
    mostrar_canal(api)
    if os.environ.get("DEMO_UPLOAD") == "0":
        linha("Rehearsal mode - authentication only, nothing uploaded.")
        return
    video = args[1] if len(args) > 1 else achar("demo_upload.mp4", "video file")
    enviar(api, video)


if __name__ == "__main__":
    main()

'@
[System.IO.File]::WriteAllText($alvo, $programa, (New-Object System.Text.UTF8Encoding $false))

$mp4 = Join-Path $pasta "demo_upload.mp4"
$b64 = @"
AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAABdQbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAF3AAAQAAAQAAAAAAAAAAAAAAAAEAAAAA
AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAC8l0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAAB
AAAAAAAAF3AAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAABQAAAALQAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAA
AAEAABdwAAAEAAABAAAAAAtBbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAyAAABLABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRl
b0hhbmRsZXIAAAAK7G1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAACqxzdGJsAAAAwHN0c2QA
AAAAAAAAAQAAALBhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABQAC0ABIAAAASAAAAAAAAAABFUxhdmM2MC4zMS4xMDIgbGlieDI2NAAAAAAAAAAAAAAA
GP//AAAANmF2Y0MBZAAf/+EAGmdkAB+s2UBQBbsBEAAAAwAQAAADAyDxgxlgAQAFaO+EcsD9+PgAAAAAEHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAAOlIA
ADpSAAAAGHN0dHMAAAAAAAAAAQAAAJYAAAIAAAAAFHN0c3MAAAAAAAAAAQAAAAEAAATAY3R0cwAAAAAAAACWAAAAAQAABAAAAAABAAAKAAAAAAEAAAQAAAAA
AQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEA
AAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAK
AAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAA
AAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAA
AQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEA
AAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAE
AAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAA
AAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAA
AQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEA
AAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAA
AAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAA
AAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAA
AQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEA
AAQAAAAAKHN0c2MAAAAAAAAAAgAAAAEAAAACAAAAAQAAAAIAAAABAAAAAQAAAmxzdHN6AAAAAAAAAAAAAACWAAAVaQAAADsAAAAlAAAAJQAAACUAAAAoAAAA
JwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgAAAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgAAAAnAAAAJQAAACUA
AAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgAAAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgAAAAnAAAA
JQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgAAAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgA
AAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgAAAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAA
JQAAACgAAAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgAAAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcA
AAAlAAAAJQAAACgAAAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAAKAAAACcAAAAlAAAAJQAAACgAAAAnAAAAJQAAACUAAAAoAAAAJwAAACUAAAAlAAAA
KAAAACcAAAAlAAAAJQAAACgAAAAnAAAAJQAAACUAAAAnAAACZHN0Y28AAAAAAAAAlQAAF4AAAC07AAAtbAAALZ0AAC3OAAAuAgAALjUAAC5mAAAulwAALsUA
AC74AAAvKQAAL1oAAC+OAAAvwQAAL/IAADAjAAAwUQAAMIQAADC1AAAw5gAAMRoAADFNAAAxfgAAMa8AADHdAAAyEAAAMkEAADJyAAAypgAAMtkAADMKAAAz
OwAAM2kAADOcAAAzzQAAM/4AADQyAAA0ZQAANJYAADTHAAA09QAANSgAADVZAAA1igAANb4AADXxAAA2IgAANlMAADaBAAA2tAAANuUAADcWAAA3SgAAN30A
ADeuAAA33wAAOA0AADhAAAA4cQAAOKIAADjWAAA5CQAAOToAADlrAAA5mQAAOcwAADn9AAA6LgAAOmIAADqVAAA6xgAAOvcAADslAAA7WAAAO4kAADu6AAA7
7gAAPCEAADxSAAA8gwAAPLEAADzkAAA9FQAAPUYAAD16AAA9rQAAPd4AAD4PAAA+PQAAPnAAAD6hAAA+0gAAPwYAAD85AAA/agAAP5sAAD/JAAA//AAAQC0A
AEBeAABAkgAAQMUAAED2AABBJwAAQVUAAEGIAABBuQAAQeoAAEIeAABCUQAAQoIAAEKzAABC4QAAQxQAAENFAABDdgAAQ6oAAEPdAABEDgAARD8AAERtAABE
oAAARNEAAEUCAABFNgAARWkAAEWaAABFywAARfkAAEYsAABGXQAARo4AAEbCAABG9QAARyYAAEdXAABHhQAAR8kAAEf6AABIKwAASF8AAEiSAABIwwAASPQA
AEkiAABJVQAASYYAAEm3AAAKsXRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAIAAAAAAAAXawAAAAAAAAAAAAAAAQEAAAAAAQAAAAAAAAAAAAAAAAAAAAEA
AAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAF2oAAAQAAAEAAAAACiltZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAA
ALuAAARoAFXEAAAAAAAtaGRscgAAAAAAAAAAc291bgAAAAAAAAAAAAAAAFNvdW5kSGFuZGxlcgAAAAnUbWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAA
ABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAmYc3RibAAAAH5zdHNkAAAAAAAAAAEAAABubXA0YQAAAAAAAAABAAAAAAAAAAAAAgAQAAAAALuAAAAAAAA2
ZXNkcwAAAAADgICAJQACAASAgIAXQBUAAAAAAfQAAAAI9wWAgIAFEZBW5QAGgICAAQIAAAAUYnRydAAAAAAAAfQAAAAI9wAAABhzdHRzAAAAAAAAAAEAAAEa
AAAEAAAAAeRzdHNjAAAAAAAAACcAAAABAAAAAQAAAAEAAAACAAAAAgAAAAEAAAAJAAAAAQAAAAEAAAAKAAAAAgAAAAEAAAARAAAAAQAAAAEAAAASAAAAAgAA
AAEAAAAZAAAAAQAAAAEAAAAaAAAAAgAAAAEAAAAhAAAAAQAAAAEAAAAiAAAAAgAAAAEAAAApAAAAAQAAAAEAAAAqAAAAAgAAAAEAAAAxAAAAAQAAAAEAAAAy
AAAAAgAAAAEAAAA5AAAAAQAAAAEAAAA6AAAAAgAAAAEAAABBAAAAAQAAAAEAAABCAAAAAgAAAAEAAABJAAAAAQAAAAEAAABKAAAAAgAAAAEAAABRAAAAAQAA
AAEAAABSAAAAAgAAAAEAAABZAAAAAQAAAAEAAABaAAAAAgAAAAEAAABhAAAAAQAAAAEAAABiAAAAAgAAAAEAAABpAAAAAQAAAAEAAABqAAAAAgAAAAEAAABx
AAAAAQAAAAEAAAByAAAAAgAAAAEAAAB5AAAAAQAAAAEAAAB6AAAAAgAAAAEAAACBAAAAAQAAAAEAAACCAAAAAgAAAAEAAACJAAAAAQAAAAEAAACKAAAAAgAA
AAEAAACRAAAAAQAAAAEAAACSAAAAAgAAAAEAAACVAAAABQAAAAEAAAR8c3RzegAAAAAAAAAAAAABGgAAABcAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAG
AAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAA
AAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAG
AAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAA
AAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAG
AAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAA
AAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAG
AAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAA
AAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAG
AAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAA
AAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAG
AAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAA
AAYAAAAXAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAG
AAAABgAAAAYAAAAGAAAABgAAAmRzdGNvAAAAAAAAAJUAAC0kAAAtYAAALZEAAC3CAAAt9gAALikAAC5aAAAuiwAALr8AAC7sAAAvHQAAL04AAC+CAAAvtQAA
L+YAADAXAAAwSwAAMHgAADCpAAAw2gAAMQ4AADFBAAAxcgAAMaMAADHXAAAyBAAAMjUAADJmAAAymgAAMs0AADL+AAAzLwAAM2MAADOQAAAzwQAAM/IAADQm
AAA0WQAANIoAADS7AAA07wAANRwAADVNAAA1fgAANbIAADXlAAA2FgAANkcAADZ7AAA2qAAANtkAADcKAAA3PgAAN3EAADeiAAA30wAAOAcAADg0AAA4ZQAA
OJYAADjKAAA4/QAAOS4AADlfAAA5kwAAOcAAADnxAAA6IgAAOlYAADqJAAA6ugAAOusAADsfAAA7TAAAO30AADuuAAA74gAAPBUAADxGAAA8dwAAPKsAADzY
AAA9CQAAPToAAD1uAAA9oQAAPdIAAD4DAAA+NwAAPmQAAD6VAAA+xgAAPvoAAD8tAAA/XgAAP48AAD/DAAA/8AAAQCEAAEBSAABAhgAAQLkAAEDqAABBGwAA
QU8AAEF8AABBrQAAQd4AAEISAABCRQAAQnYAAEKnAABC2wAAQwgAAEM5AABDagAAQ54AAEPRAABEAgAARDMAAERnAABElAAARMUAAET2AABFKgAARV0AAEWO
AABFvwAARfMAAEYgAABGUQAARoIAAEa2AABG6QAARxoAAEdLAABHfwAAR6wAAEfuAABIHwAASFMAAEiGAABItwAASOgAAEkcAABJSQAASXoAAEmrAABJ3gAA
ABpzZ3BkAQAAAHJvbGwAAAACAAAAAf//AAAAHHNiZ3AAAAAAcm9sbAAAAAEAAAEaAAAAAQAAAGJ1ZHRhAAAAWm1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1k
aXJhcHBsAAAAAAAAAAAAAAAALWlsc3QAAAAlqXRvbwAAAB1kYXRhAAAAAQAAAABMYXZmNjAuMTYuMTAwAAAACGZyZWUAADKEbWRhdAAAAq0GBf//qdxF6b3m
2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjQgcjMxMDggMzFlMTlmOSAtIEguMjY0L01QRUctNCBBVkMgY29kZWMgLSBDb3B5bGVmdCAyMDAzLTIwMjMgLSBo
dHRwOi8vd3d3LnZpZGVvbGFuLm9yZy94MjY0Lmh0bWwgLSBvcHRpb25zOiBjYWJhYz0xIHJlZj0xIGRlYmxvY2s9MTowOjAgYW5hbHlzZT0weDM6MHgxMTMg
bWU9aGV4IHN1Ym1lPTIgcHN5PTEgcHN5X3JkPTEuMDA6MC4wMCBtaXhlZF9yZWY9MCBtZV9yYW5nZT0xNiBjaHJvbWFfbWU9MSB0cmVsbGlzPTAgOHg4ZGN0
PTEgY3FtPTAgZGVhZHpvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9tYV9xcF9vZmZzZXQ9MCB0aHJlYWRzPTYgbG9va2FoZWFkX3RocmVhZHM9MiBzbGlj
ZWRfdGhyZWFkcz0wIG5yPTAgZGVjaW1hdGU9MSBpbnRlcmxhY2VkPTAgYmx1cmF5X2NvbXBhdD0wIGNvbnN0cmFpbmVkX2ludHJhPTAgYmZyYW1lcz0zIGJf
cHlyYW1pZD0yIGJfYWRhcHQ9MSBiX2JpYXM9MCBkaXJlY3Q9MSB3ZWlnaHRiPTEgb3Blbl9nb3A9MCB3ZWlnaHRwPTEga2V5aW50PTI1MCBrZXlpbnRfbWlu
PTI1IHNjZW5lY3V0PTQwIGludHJhX3JlZnJlc2g9MCByY19sb29rYWhlYWQ9MTAgcmM9Y3JmIG1idHJlZT0xIGNyZj0zMC4wIHFjb21wPTAuNjAgcXBtaW49
MCBxcG1heD02OSBxcHN0ZXA9NCBpcF9yYXRpbz0xLjQwIGFxPTE6MS4wMACAAAAStGWIhAA3/7HAazub4DW3B8d7dvVKzzZjIkMLeCKpJ7/smoAAAAMAAAMA
AAMAAAMAQ73iOKcfqjxBZAAAAwAAAwLoAAW8AA3gACxAAKgAArgAD+AATIACGgAPsABigAOsAAADAAADAAADAAADAAADAAADAAADApZDZoM2YAikpox16/+v
Z6ngrykC72lFpwqmhyIOybtZuo1pM6huX37vvFCPKRXq3TZEK0wz/CPX7QqoT42tZ2yD9S9kD6lHrgOV9MfIJkLOCBVf6h0d9sStlkizBqLcpz9vYu0kIoUL
ZQR0rUKu797JmufgQlBFmVMRTmVURltsKcTP4EBG5dp9DwupFsHvVCOo0RFdhDgtZyaiVlpRX+ZmPjY2yoNvOn570MT0Xfe2BZLEZNBbKDMOCv2HG08zvSVr
JmSd9b2TvjCAXnxl7eRQZBjYqYFI0vPJ2eLPaZD4a+bX3FiHy3Yc4V+mMWdqoDEiJUJqbomFUoYQuArqAyl/Qw/Emouv4sDfhUhXwd+AItyb2qXbQ44PogYy
Nj8qbmPHatvYmJJtkFIe37o8A+g4YAe77Hy7GT8z8/7X8/t/KBhrflrE/FHG7awoPZkj4fHASXR3/AmKixRYX7lLuiPObAdCQAIdzRHu7i4oou6KNqqC+Jpk
AEEM1oqYhdvGKg2Y0TZQ+DCFqIgViIeD+gtuagrU2WZbHVH+/KhqI606aXSGBtvYJ0QY0rK8uNTs74ZpWbexAGb9sb/9Kz3fmavKlon5rDGH2/C+qEEFJUOo
o5R38/D7FFKjnUMOJN5VKcYiRR/NdZUigtwwdUtUvfxLVgYrZEpCAUZRaWQy33tv9mD4nCpsKR9m1UE6xvNbiAFHLBZ/vsSCn4gqy9D3Kdp4CSZAxB4qDg7B
3U7NGPxwQbPfA0TMl5Br6hjS5VKlwU+6OCO2U5IuBgkVVbuXe1CerIKXUOp7MKkpOPPCK7q4NM8FPtntoKnLz2XDa7s+pic8zZ085HS+U86uuyg3g1l+qozZ
64gYEbyRJ2oJ7UPdxbTIbSKiOmCCDpOqTdahMPx/PQ+SIsb8v/53tNL+HzS50/RA8aezEZ5sQSHrzaiCFU6tpSK+YAWpIwj5qckjvK9TuqvnRU64JYDIFZiD
zfjMu3TAL/tfiENGbHf2QMU4lWpzeuefdhaR3FgpYLJ8kfS2iNxx2MbzPnMYDCBvMk4wFJ3iPmoe69rZTrPyluaNmeMD/Eql1RXiXx9WWA9BLGQD/c/9JSNQ
DAGh/IifQeOz3dYp4pvEXvgtb14lgFvh7eYYai+SX/Y9Lwl+27YPbFo2hw20GVm+ddl/juFz1Bvey8utdCIC6RkoHULoouMU8U86WsYnCuT01vEk9VjySib1
ItP08GFJlg7XtCBsZknNeHJzKA0uU1TDJg+1kz5aBJpDMLCSTRiGmpaRw6MC3DCdbF9DSzvQ3iykYUuKS/lBsiK/HWRqqwa23DVBJvdnbYP30agRzkuL1NEr
JhtpfsQ8rgZ+jdzFcely+ByMjHRoqrC/X56/slm3a2cKyUXKO+DgK7OtHAPVKRXCIUMBr5Fb3tMHd251FAkzz1MNb3TU5C2DHTYQbh/fgDjMeZcYhLwFzk+V
h7XrzcP06ciC3b1eRxKhBoP6knNfULAsYkIvJoPPf57xpiF2nQ2ssRJ4jY/99gu6S8FzD5dixhxJLztvJHe2iurcAUpZuwoN4dsmcOx2z3oMg/81AfLfql7j
xS1aVLsLWb40+eLX1PaiHp99pw1QYUR6+6E8d7JUQU6eZc6i7P4TruK6qjYJMe1L9tm9IAfyexP7aWGX1BM6FGf7Ha+YElHmBDQZ275MNsyekV9uW95hmd9H
M3QRUuTSTRd7T1Mxd0uxxeyMbBQnhBf4qJqu3cvchuCD18368Yrm9l5RSvH58NcUGB/tPWcQyyapPneii3RoAHP3jnWNFe6E70BMbtY7+WI7tkv5dqsqiXCA
6DVrOhJ+lQCJJ8qZUenCeFcdhPfWw/+IgQ+x89yQ5fEx2Cff84vaCUHdW1CWnaI7+8LfjfnsGpN1yKSm8A4Ogy3R7xjGaQZ94KErX7SIaIuNAKWVKx9puBMH
/K76z8iIaBeE7YfKOZl9YikUpg2mn6s30BYi7GCGOt8jQJr2HHxFE1PCjgr2zVeE3W3fYpPizCAm2gm2iup/m3GH4hnN0H7/UbQWa6TTH3veJrKkqXVANY8A
2RRgUVJabBHHirzwaVKtouPZZYP7U5P85VQWKkftKbM+4IX06d11hMPMNHxeqlShmZTb4RzZOg/aau41AQ6FHqePNPadelQFBbXvnfc9CcGk3XWUKoYkOxn6
FL9z2zBQI6TzfhtzJO1T3zt2XJ89V37Xbmll8Y3Ip6Xvunriy7m2oPNhb8N2/EMBFP53TQ5dggebQudCbfwfZ8d5e9UrmP44q2U+AJWLGMXQ5Zlm9g+3Zx7w
v5XRHlA1gaCVjJYsf4Yii+ydssyOVjBSc/6EfCcnneJx5SGtA8Cz8ICZZOSqeh0t0WiG6eioQhpQn45gIXb34fG/C3QJeUg9ECWHcBTKXlOGUuRlknpEt/ox
qSIH3nlt6wx99Wq4jUn2veYnm1G0c3Y/L/+ucy7FUY1x0OC1qD1t9Mwgmny+venJRvoDiyfcLnuM3/EU0n02ixL5KOpkPPUnTRg9hBHX8dWkbGtRtbyOtbok
Jf9F+gquJKukcw+6ftor6tXhouRk6Wzv9jiAPnpbY2jgZAUHCVTsTVHAzYNgUxyVDHfP6V8k+qxQASNYLkhExkZwhveSgf6R4WlgPyBbiRnp6QfmuFlv4j0I
5Clu0fWOmMZ4w4VbC0IqtYCckakGNv2gDA/tzc0j6JGHVJumRA9FDaaM8JDhrELKBqyuaQRoapf5eftA9zCTMlg1JTaChaS2uVaxsHjsIezHik+o1sR6Hzve
wpT1LmU0l6GNQ5rm6WEs5mKig8RfpMVjNZW7MZyVzKE4pTHjBaw81Mwpy4sEvlrsHdkJOFpwhmGCllntSdFhOzn3REIFKOvTJ03R3JEcXrTwRBycPXM2L0Q0
9v2TXa5MJcbBEFk0ref9rxxcBP1RsTIeI0dMONgA7G8sA6khWky3BT0FfShtGiK9CHuMYyOU4toqeWeO8MCXP94Pv7Kk1CduFCv0BJUNTryHUqbdHje+PrOD
N07bI58JZFqtdaQyiwHWp2ozbO4YgTNPDms3G20PZaY2WzNWpab7wzA4xRjXCwbSZA7kJq7DVhGQqmC2Rn+LhBOYYHRfoP7PciZPaGmXl2hGlKFxNkOENbAO
Q2zwYIWCbsTsrak+LmUU6zFjr4oD32pMRNZq6E74J37UfiNxSJsZ2IfW/ldlVkJUNVXEdys53sKWuAPJvWF0VepCVVPvwbUjhEwBCETJulu5IYVenDZGFnba
ekpefHK4qvQl9fug+0YC5HEE3TtygId1mg0HXw3DekWl8PoSHzFNZUL6mJ7RcngyMuxuiuepKdeFYpzyMzVcH42LVx739bDeBezXVpyeI2ZOkztyWfNpKAuR
MVtH4qH2nJdUQWOAup3E1uNuBa4AfDgHvfq0AOCjvm4uNonUbOtpVEVcPwl38DHaHtvRJhRT5CvkoU7ONhZlzgbQmYXd7JLkB0XxfGR8Pwa8UTRlPlStIjK/
PN2cFJQ/QUJMudOA+1HUZ4rnNFAWiZ9x2rOJpMe48/sgfhzBupjEKDfwwDy13e44tKS636nPQzC1eaMDTeyqjuxcRU6xETNQGRIWpngug2vYiClrKzwp1gOs
T3zdEo27BX3wd61IJxd5eYgwTlhOLqUk9NyR7+wFLm+98mF6gCzPvtv8y/zDmoo7+bLjatk9SVT9I/3O32VnJVWrp7iuotpFdPzRdoddx+KPV6c1g3bwDNu/
dT/55MsJKSFHr2yGFdSxQdlBaa3eAVrB+YH5C+DKJBJSL3U++Ol0f/MSWokKIkaE7SeCAHpYRQiOhwPTPNXTX7Jtg1iTMSWmj5YvA9YdnTQAp9Vwd388xK2L
+sMrogdvoobj0rLrJo830x2bgtHW6l0gO3oA7Z54JKNBH5rVRPESxpuh371SxCnECbN79iwghuEZZ6PgAAAYUAFJ/31XEa18VpCaALhwhWmDKPd3LlX9feme
GEiEdMZuNNHdhfpL9MtOnq8pvHNQMwu6Bgg1evWqIdE2k1x0x/JfZ4VhlfQx7v8BzLK2MC0xuD7U8IElhQbnhhYLAdKVjydM7XDwgKBJfElD3WhNunPkxih0
ZvczRdSwCpeIwAbMbNcW1whNe7d90sOti2gw5/+2tjekvCjF8773bjtZh7vKNrDuQMaNRTNZHEM4K+0QSS7KLeQbPXVePLcO+cFmU+8oCVnhl2p7w89L/23C
E1p/7xCSlAVyqxhxTSr6AcOrZ7LAQavicXpib7AAAAqut2NhpM4Hs35j7+9bbf67xXcUncrXL8Aakzt36X9ZYRg/lTIXEJShRqZnQtvHR3001A8cylLi/Tc/
4vNH2CVRh5375iv9W83UWauTW9ynOQwzvbyjEIeQkn0W0DRqs1YJMK6hirVCvuty7+8I+33dMGGHtjmRWM8Cc+RYfMuTvFA306yQ+7D05RhVI1DLNsjUvKto
5+n1E5c6/PdP7h87R/r+k38mr3gHVicoc7MQe/uwozQWI4PkP0KrXPwfX92i/aETkwB1KrYdOvon/oQHMQYbdXpTN5qFgHd1YwR8/nteIkWD68VDb1kcR172
kuCCOFspBxwmuUOalAQTKQM8sMQrR651FX6w7k7oc7MYIppRweoiElriWQbwJuoa9HOG5KRlPQj8RAEAXrelY7aV6imrsqAoEOGMGtspz1I516d/oL1o+y3w
rGlzjHTAFIjQAXpvzF0Q7a8VfB8IQqdozMhBXbNzJgvTruk2dUyLuc1T4xayLAmbs0WZUD1xAlvfav9kwviYZrIwRN0zzrz2lmHDSGEheOIr6SAfHPneWwS3
/AZDENEV2gsKWhDOQgGiBw5DqCyv4YkVB8vFBRmh5cWVofKPg9xYoECkUzqcTYZpsZStEjPxFN93mlS5H48syi6henQuPUn9vhXARPHHr5bGN8+G/EgCJ5jo
LGOcjepdFLClAM07foro52RDkdBb8Iu0PPtQJH6wPzk1YluDiM9n2eAgdHYtpZqMEZnBAGQSOheFowv9I2tamesPDfsEoF6nHymLg0eSN+MsTcYNkXFVYRXf
hxtiHX2+or11UO+6veuUBfYqS/tnzYYLMHL9LiPIpppYJF/jWSE8/Zafz/JeAuWrE/iyqpI72bcXXCsPFBJlaP5O/Lyo3sHlH60Y+A6e/tXS6B0YbJOnQrBn
1zZrPC1oXAE4rl1EsIAdOXsjCGZikqrgakNEhhtrf28pc4PKN3iVnONUtLmdFlP52x4dDfGeUr0Coj2XPY/qTGyapyUXHX+SAROWGla1/SK1C3TGy9xNiOkU
JQsNeinIFaHiEuJZ6QbH08vehuNxuGkK7xnuIv5ezleqIGqNChvqWiuV706R0I3fIb3SFxxnEqD/zGxX8j2BfaHoeUPb02sa5UUfxQQfBqLCrfU5GGTLdqge
yPEH9MS0W9a6ivomULJImA53wtbH09oxF3p1cOrpf7MqqrVNVw5xWZtVxawGImBeUgxCKa6AHpcuLvmpWN+jki1YLVekJ8Y8Ni7Dew5PCPt+y37vnlCKNFSy
qJT/ZmbeD/aFt47/ov5sgx4+kI8xh+BRN5Kc8zBo/MbO+aHKBR6UQosR8SFUo8UkFnViubuOG1WkAOTEsO+4YNdv6vXpF1KNmo6WniTc3go1cTqvqP/II4Ma
1iWGyU901xWTB3EPD2X6asweNk41auJNiIz5eAGcxETPYTSz8x68oLpwuRu0hTgM7eyO0EwbeOFvyzvcgsc7YkRx0WsmAPHwEiLP5lmteqojagG5jZLl7czd
654ur2EgS3s+/R3T3IIM36j75g4gtLBA+iVwV2adUyniVRX6yrvmJR3vkWGeKA4rMsklCjzokN0Caay/KN+bXG8t6isKWnb0kceB7kKIhPXXygVmfLm9BhTD
EcWu7NBsinm7Byme8JwYxbLUdfcje26lisc17WYix8TxgqF1v/FOYbGcjwdPPLW7rhVQ2EtcVTq6ORlMDAJEbeevXsUl3dKEXm8lijZ7Kv2dXOHOWSxGYcvX
0MU/K7YRwWrZZ71y3UJQIrTzBKCgm1ppjBAIr9xyVDgUOrsHYNO95T9bbGOffh4BFQW+M+oYf9udmT3ALiIsTlLJP87Q8YK7Z8nQwCrR7OkW2gBYErQrVaAA
AAfKxAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwABZwAAADdBmiQYhv/6WAAAAwAAAwAAAwAA
AwALbe0ACv68//ofzELEjYgjO1ummvL00RkUAAADAAADAAVM3gIATGF2YzYwLjMxLjEwMgBCIAjBGDgAAAAhQZ5CQhf/AAADAAADAAADAAADAAADAAADAAAD
AAADAKqBIRAEYIwcIRAEYIwcAAAAIQGeYUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBnmNEK/8AAAMAAAMAAAMAAAMA
AAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZpoNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GehkURLC//
AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGepUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAA
ACEBnqdEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZqsNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAE
YIwcAAAAI0GeykUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGe6UQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDP
gCEQBGCMHCEQBGCMHAAAACEBnutEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZrwNExDf/pYAAADAAADAAADAAADAAAD
AAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GfDkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGfLUQr/wAAAwAA
AwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAAACEBny9EK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZs0
NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GfUkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwc
AAAAIQGfcUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBn3NEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARg
jBwhEARgjBwAAAAkQZt4NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GflkUVLC//AAADAAADAAADAAADAAADAAAD
AAADAAADAKqAIRAEYIwcIRAEYIwcAAAAIQGftUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAAACEBn7dEK/8AAAMAAAMAAAMA
AAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZu8NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0Gf2kUVLC//AAAD
AAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGf+UQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEB
n/tEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZvgNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwc
IRAEYIwcAAAAI0GeHkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqAIRAEYIwcIRAEYIwcAAAAIQGePUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAA
AwDPgCEQBGCMHCEQBGCMHAAAACEBnj9EK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZokNExDf/pYAAADAAADAAADAAAD
AAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GeQkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGeYUQr/wAAAwAAAwAA
AwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBnmNEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZpoNExD
f/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GehkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAE
YIwcAAAAIQGepUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAAACEBnqdEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4Ah
EARgjBwhEARgjBwAAAAkQZqsNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GeykUVLC//AAADAAADAAADAAADAAADAAADAAAD
AAADAKqBIRAEYIwcIRAEYIwcAAAAIQGe6UQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBnutEK/8AAAMAAAMAAAMAAAMA
AAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZrwNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GfDkUVLC//
AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGfLUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAA
ACEBny9EK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZs0NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAE
YIwcAAAAI0GfUkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGfcUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDP
gCEQBGCMHCEQBGCMHAAAACEBn3NEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZt4NExDf/pYAAADAAADAAADAAADAAAD
AAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GflkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqAIRAEYIwcIRAEYIwcAAAAIQGftUQr/wAAAwAA
AwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAAACEBn7dEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZu8
NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0Gf2kUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwc
AAAAIQGf+UQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBn/tEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARg
jBwhEARgjBwAAAAkQZvgNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GeHkUVLC//AAADAAADAAADAAADAAADAAAD
AAADAAADAKqAIRAEYIwcIRAEYIwcAAAAIQGePUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBnj9EK/8AAAMAAAMAAAMA
AAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZokNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GeQkUVLC//AAAD
AAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGeYUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEB
nmNEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZpoNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwc
IRAEYIwcAAAAI0GehkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGepUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAA
AwDPgSEQBGCMHCEQBGCMHAAAACEBnqdEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZqsNExDf/pYAAADAAADAAADAAAD
AAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GeykUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGe6UQr/wAAAwAAAwAA
AwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBnutEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZrwNExD
f/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GfDkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAE
YIwcAAAAIQGfLUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAAACEBny9EK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4Ah
EARgjBwhEARgjBwAAAAkQZs0NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GfUkUVLC//AAADAAADAAADAAADAAADAAADAAAD
AAADAKqBIRAEYIwcIRAEYIwcAAAAIQGfcUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBn3NEK/8AAAMAAAMAAAMAAAMA
AAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZt4NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GflkUVLC//
AAADAAADAAADAAADAAADAAADAAADAAADAKqAIRAEYIwcIRAEYIwcAAAAIQGftUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAA
ACEBn7dEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZu8NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAE
YIwcAAAAI0Gf2kUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGf+UQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDP
gCEQBGCMHCEQBGCMHAAAACEBn/tEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZvgNExDf/pYAAADAAADAAADAAADAAAD
AAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GeHkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqAIRAEYIwcIRAEYIwcAAAAIQGePUQr/wAAAwAA
AwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBnj9EK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZok
NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GeQkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwc
AAAAIQGeYUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBnmNEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARg
jBwhEARgjBwAAAAkQZpoNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GehkUVLC//AAADAAADAAADAAADAAADAAAD
AAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGepUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAAACEBnqdEK/8AAAMAAAMAAAMA
AAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZqsNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GeykUVLC//AAAD
AAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGe6UQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEB
nutEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZrwNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwc
IRAEYIwcAAAAI0GfDkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGfLUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAA
AwDPgSEQBGCMHCEQBGCMHAAAACEBny9EK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZs0NExDf/pYAAADAAADAAADAAAD
AAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GfUkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGfcUQr/wAAAwAAAwAA
AwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBn3NEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZt4NExD
f/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GflkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqAIRAEYIwcIRAE
YIwcAAAAIQGftUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAAACEBn7dEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4Eh
EARgjBwhEARgjBwAAAAkQZu8NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0Gf2kUVLC//AAADAAADAAADAAADAAADAAADAAAD
AAADAKqBIRAEYIwcIRAEYIwcAAAAIQGf+UQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACEBn/tEK/8AAAMAAAMAAAMAAAMA
AAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZvgNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GeHkUVLC//
AAADAAADAAADAAADAAADAAADAAADAAADAKqAIRAEYIwcIRAEYIwcAAAAIQGePUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAA
ACEBnj9EK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZokNExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAE
YIwcAAAAI0GeQkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGeYUQr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDP
gCEQBGCMHCEQBGCMHAAAACEBnmNEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4EhEARgjBwhEARgjBwAAAAkQZpoNExDf/pYAAADAAADAAADAAADAAAD
AAADAAADAAADAFVBIRAEYIwcIRAEYIwcAAAAI0GehkUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqBIRAEYIwcIRAEYIwcAAAAIQGepUQr/wAAAwAA
AwAAAwAAAwAAAwAAAwAAAwAAAwDPgSEQBGCMHCEQBGCMHAAAACEBnqdEK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARgjBwhEARgjBwAAAAkQZqs
NExDf/pYAAADAAADAAADAAADAAADAAADAAADAAADAFVAIRAEYIwcAAAAI0GeykUVLC//AAADAAADAAADAAADAAADAAADAAADAAADAKqB3gIATGF2YzYwLjMx
LjEwMgBCIAjBGDghEARgjBwAAAAhAZ7pRCv/AAADAAADAAADAAADAAADAAADAAADAAADAM+AIRAEYIwcIRAEYIwcAAAAIQGe60Qr/wAAAwAAAwAAAwAAAwAA
AwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACRBmvA0TEN/+lgAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAVUEhEARgjBwhEARgjBwAAAAjQZ8ORRUsL/8A
AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAqoEhEARgjBwhEARgjBwAAAAhAZ8tRCv/AAADAAADAAADAAADAAADAAADAAADAAADAM+BIRAEYIwcIRAEYIwcAAAA
IQGfL0Qr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACRBmzQ0TEL/8yAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAz4AhEARg
jBwAAAAjQZ9SRRUsL/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAqoEhEARgjBwhEARgjBwAAAAhAZ9xRCv/AAADAAADAAADAAADAAADAAADAAADAAADAM+A
IRAEYIwcIRAEYIwcAAAAIQGfc0Qr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwDPgCEQBGCMHCEQBGCMHAAAACNBm3U0TEK/5EAAAAMAAAMAAAMAAAMAAAMA
AAMAAAMAAAMCgyEQBGCMHCEQBGCMHCEQBGCMHCEQBGCMHCEQBGCMHA==
"@
[System.IO.File]::WriteAllBytes($mp4, [Convert]::FromBase64String(($b64 -replace "\s", "")))
Write-Host "  ok  programa e video de teste gravados" -ForegroundColor Green

# ----------------------------------------------------------------- 5. rodar
Write-Host ""
Write-Host "  1 = ENSAIO   (so testa o login, nao envia nada)"
Write-Host "  2 = GRAVAR   (ligue o gravador de tela antes)"
Write-Host ""
$op = Read-Host "Digite 1 ou 2"

if ($op -eq "2") {
    # Apaga o login guardado. Com token valido o script pula a tela de
    # consentimento - que e o unico quadro que o revisor precisa ver.
    Remove-Item (Join-Path $pasta "token.json") -ErrorAction SilentlyContinue
    Write-Host ""
    Write-Host "  >> LIGUE O GRAVADOR DE TELA AGORA <<" -ForegroundColor Yellow
    Read-Host "Enter quando estiver gravando"
    $env:DEMO_UPLOAD = "1"
} else {
    $env:DEMO_UPLOAD = "0"
}

Write-Host ""
& $py $alvo
Write-Host ""
Read-Host "Enter para fechar"
