"""Blocos narrativos do setiap-level-005, separados do gerador.

Dimensionados pelo modelo medido em 2026-08-05 (duracao = chars/20,58 +
frases x 0,96), nao pela tabela de chars/s do PLAYBOOK, que erra ate 21%.
Alvo 840s. A ultima cena de cada bloco termina em pergunta ou dois-pontos.
"""

BLOCOS = [
 ("Kenaikan yang hilang", [
  ("titulo", "Gajimu naik", "bulanmu sama",
   "Tahun ini gajimu naik. Angkanya nyata, tercatat hitam di atas putih pada slip yang kamu terima, dan selama beberapa hari pertama kamu benar-benar merasa lega."),
  ("titulo", "Lalu bulan berjalan", "seperti biasa",
   "Lalu bulan berjalan seperti biasa. Di minggu ketiga kamu sudah mulai menghitung lagi, memilih mana yang bisa ditunda sampai tanggal muda. Persis seperti tahun lalu, dengan gaji yang lebih kecil."),
  ("item", "Yang hilang", "bukan disiplinmu",
   "Penjelasan yang paling sering kamu dengar adalah bahwa kamu kurang disiplin, bahwa ada kebocoran kecil yang tidak kamu sadari, bahwa kopi dan langganan itu yang menghabiskan semuanya."),
  ("titulo", "Penjelasan itu", "terlalu mudah",
   "Penjelasan itu nyaman karena menutup perkara dengan cepat dan meletakkan seluruh bebannya pada satu orang. Tapi ia tidak menjelaskan kenapa jutaan orang mengalami hal yang sama, di bulan yang sama, dengan pola yang sama."),
  ("titulo", "Kalau semua orang gagal", "di titik yang sama",
   "Kalau begitu banyak orang gagal di titik yang persis sama, yang sedang kamu lihat bukan kumpulan kesalahan pribadi. Yang sedang kamu lihat adalah sebuah struktur."),
  ("lista", "Lima bagian", ["Rumus kenaikanmu", "Keranjang belanjamu", "Biaya yang menempel", "Bunga", "Yang menyusut duluan"],
   "Struktur itu punya lima bagian, dan setiap bagian bisa dihitung dengan angka yang berlaku sekarang, bukan dengan perkiraan."),
  ("item", "Semua angka di sini", "angka dua ribu dua puluh enam",
   "Semua angka dalam video ini adalah angka tahun berjalan, dari lembaga resmi, dan setiap sumbernya saya tulis di deskripsi supaya bisa kamu periksa sendiri."),
  ("item", "Pertanyaannya", "ke mana perginya",
   "Kalau gajimu naik tujuh persen dan hidupmu terasa sama, uang itu tidak menguap begitu saja. Ia pindah ke suatu tempat yang punya nama dan punya angka. Ke mana?"),
 ]),
 ("Rumus yang menentukan kenaikanmu", [
  ("titulo", "Kenaikan upah", "punya rumus tertulis",
   "Kenaikan upah minimum bukan angka yang dipilih oleh seseorang berdasarkan perasaan. Ia keluar dari sebuah rumus, dan rumus itu tertulis serta bisa dibaca siapa saja."),
  ("lista", "Bahannya tiga", ["Inflasi", "Pertumbuhan ekonomi", "Indeks alpha daerah"],
   "Bahannya tiga: inflasi, pertumbuhan ekonomi, dan sebuah indeks daerah yang disebut alpha. Ketiganya digabung menjadi satu angka kenaikan."),
  ("item", "Susunannya", "inflasi ditambah pertumbuhan dikali alpha",
   "Susunannya begini. Inflasi ditambah hasil perkalian antara pertumbuhan ekonomi dan indeks alpha daerahmu."),
  ("item", "Indeks alpha", "antara nol koma lima dan nol koma sembilan",
   "Indeks alpha bergerak antara nol koma lima dan nol koma sembilan, menyesuaikan kondisi ekonomi tiap wilayah. Semakin kuat daerahmu, semakin besar porsi pertumbuhan yang ikut masuk."),
  ("item", "Hasil nasionalnya", "lima sampai delapan persen",
   "Hasil nasionalnya untuk tahun ini berada di kisaran lima sampai delapan persen, ditetapkan lewat surat keputusan gubernur di akhir tahun sebelumnya."),
  ("titulo", "Sampai sini", "rumusnya masuk akal",
   "Sampai di sini rumusnya masuk akal. Ia menjaga daya beli terhadap kenaikan harga, lalu menambahkan sedikit bagian dari pertumbuhan supaya pekerja ikut menikmati ekonomi yang membesar."),
  ("titulo", "Sekarang perhatikan", "bahan pertamanya",
   "Sekarang perhatikan bahan pertamanya lebih dekat. Inflasi. Bukan inflasi yang kamu alami di warung dekat rumah, melainkan inflasi yang diukur secara nasional."),
  ("item", "Angka resminya", "tiga koma tiga empat persen",
   "Angka resminya untuk Juni tahun ini adalah tiga koma tiga empat persen secara tahunan, tercatat oleh badan statistik dan dipakai sebagai rujukan semua kebijakan."),
  ("titulo", "Angka itu adalah", "sebuah rata-rata",
   "Angka itu adalah sebuah rata-rata. Dan rata-rata, menurut definisinya, adalah satu bilangan yang berdiri di tengah ribuan bilangan lain, sebagian jauh di bawahnya, sebagian jauh di atasnya."),
  ("barras", "Yang dirata-ratakan", ["Elektronik", "Pakaian", "Pangan", "Transportasi"], [30, 45, 80, 95],
   "Harga elektronik dan pakaian bergerak pelan, dan itu menahan rata-rata ke bawah. Harga pangan dan transportasi bergerak jauh lebih cepat, dan itu mendorongnya ke atas."),
  ("item", "Yang keluar", "satu angka di tengah",
   "Yang keluar dari penggabungan itu adalah satu angka di tengah, yang tidak menggambarkan pengalaman siapa pun secara persis. Termasuk pengalamanmu."),
  ("titulo", "Gajimu diindeks", "ke titik tengah itu",
   "Gajimu dinaikkan mengikuti titik tengah itu. Bukan mengikuti daftar barang yang benar-benar keluar dari dompetmu setiap minggu."),
  ("titulo", "Jadi pertanyaannya berubah", "dan jadi lebih tajam",
   "Jadi pertanyaannya bukan lagi berapa persen kenaikanmu. Pertanyaannya menjadi: seberapa mirip keranjang belanjamu dengan keranjang rata-rata?"),
 ]),
 ("Keranjangmu bukan keranjang rata-rata", [
  ("titulo", "Mari bongkar", "satu bulan saja",
   "Mari bongkar satu bulan saja, sampai ke bagian-bagiannya. Juni tahun ini, inflasi bulanan tercatat nol koma empat empat persen."),
  ("item", "Penyumbang terbesar", "kelompok transportasi",
   "Penyumbang terbesarnya bukan pangan dan bukan perumahan. Penyumbang terbesarnya adalah kelompok transportasi, dengan kontribusi nol koma dua delapan persen."),
  ("barras", "Dari total 0,44", ["Transportasi", "Semua sisanya"], [64, 36],
   "Artinya lebih dari separuh kenaikan harga di bulan itu datang dari satu kelompok saja, sementara seluruh kelompok lain berbagi sisanya."),
  ("lista", "Dua pemicunya", ["Harga bahan bakar", "Tarif tiket pesawat"],
   "Pemicunya dua, dan keduanya disebut secara eksplisit dalam laporan: harga bahan bakar dan tarif tiket pesawat."),
  ("titulo", "Tiket pesawat", "mungkin bukan urusanmu",
   "Tiket pesawat mungkin bukan urusanmu sama sekali. Mungkin kamu naik pesawat sekali dalam dua tahun, atau tidak pernah."),
  ("titulo", "Tapi bahan bakar", "urusanmu setiap hari",
   "Tapi bahan bakar adalah urusanmu setiap hari, entah lewat tangki motormu sendiri, lewat ongkos angkutan umum, atau lewat harga barang yang harus diangkut sampai ke tokomu."),
  ("item", "Coba hitung", "berapa hari kamu tidak bergerak",
   "Coba hitung sendiri. Dalam satu bulan, berapa hari kamu sama sekali tidak mengeluarkan uang untuk bergerak dari satu titik ke titik lain?"),
  ("item", "Untuk yang bekerja", "jawabannya mendekati nol",
   "Untuk hampir semua orang yang bekerja di luar rumah, jawabannya mendekati nol. Ongkos bukan pengeluaran bulanan. Ongkos adalah pengeluaran harian yang menyamar jadi bulanan."),
  ("titulo", "Di sinilah jurangnya", "terbuka",
   "Di sinilah jurang itu terbuka. Rata-rata nasional menjumlahkan orang yang bekerja dari rumah dan orang yang menghabiskan dua jam sehari di jalan, lalu membaginya rata."),
  ("item", "Kamu berdiri", "di salah satu sisi",
   "Kamu berdiri di salah satu sisi jurang itu, bukan di tengahnya. Tapi kenaikan gajimu dihitung dari tengahnya."),
  ("titulo", "Selisih itu", "tidak pernah muncul di slip",
   "Selisih antara inflasi rata-rata dan inflasi yang kamu alami tidak pernah muncul sebagai baris di slip gajimu. Ia muncul sebagai perasaan bahwa bulanmu lebih pendek dari seharusnya."),
  ("titulo", "Dan transportasi", "baru pos pertama",
   "Dan transportasi baru satu pos. Ada pos lain yang perilakunya jauh lebih aneh, karena ia tidak menunggu harga pasar:"),
 ]),
 ("Biaya yang ikut naik bersama gajimu", [
  ("titulo", "Ada biaya", "yang menempel pada penghasilan",
   "Ada jenis biaya yang tidak naik karena harga di pasar berubah. Ia naik karena penghasilanmu naik. Ia menempel pada gajimu seperti bayangan."),
  ("lista", "Tiga pos yang membesar", ["Pangan", "Perumahan", "Iuran dan pajak"],
   "Data struktur pengeluaran rumah tangga menunjukkan tiga pos yang porsinya membesar dalam lima tahun terakhir, dibanding sebelumnya: pangan, perumahan, serta iuran dan pajak."),
  ("item", "Iuran dan pajak", "dihitung sebagai persentase upah",
   "Iuran dan pajak yang dipotong dari gaji dihitung sebagai persentase dari upah. Upah naik, potongan ikut naik pada hari yang sama, tanpa keputusan apa pun darimu."),
  ("titulo", "Itu bukan kesalahan sistem", "itu memang desainnya",
   "Itu bukan cacat dalam sistem, itu memang cara kerjanya. Tapi efeknya nyata: sebagian kenaikanmu sudah hilang sebelum uangnya sampai ke rekening."),
  ("titulo", "Perumahan", "bergerak lewat jalur lain",
   "Perumahan bergerak lewat jalur yang berbeda. Jalurnya lebih pelan, tapi lebih dalam, dan hampir selalu satu arah."),
  ("item", "Sewa disesuaikan", "tiap kontrak diperpanjang",
   "Sewa disesuaikan setiap kali kontrak diperpanjang, dan penyesuaiannya mengikuti kondisi daerah serta permintaan di sekitarmu, bukan mengikuti kondisi dompetmu di bulan itu."),
  ("titulo", "Lalu ada jenis ketiga", "dan ini keputusanmu",
   "Lalu ada jenis ketiga, dan yang ini memang keputusanmu sendiri. Tapi ia bukan keputusan yang kamu sadari sedang kamu ambil."),
  ("lista", "Perubahan yang menetap", ["Kos lebih dekat kantor", "Satu langganan baru", "Makan di luar sekali lagi"],
   "Pindah kos yang lebih dekat kantor supaya tidak berangkat pukul lima pagi. Satu langganan baru. Satu kali makan di luar tambahan setiap minggu."),
  ("item", "Masing-masing wajar", "dan memang wajar",
   "Masing-masing terasa wajar, dan sejujurnya masing-masing memang wajar. Setelah bertahun-tahun bertahan, sedikit ruang bernapas bukan kejahatan."),
  ("titulo", "Yang perlu diperhatikan", "bukan wajar atau tidak",
   "Yang perlu diperhatikan bukan soal wajar atau tidak wajar. Yang perlu diperhatikan adalah sifat biaya itu setelah ia masuk."),
  ("item", "Sekali naik", "ia jadi lantai baru",
   "Biaya seperti ini tidak turun lagi ketika bulanmu memburuk. Sekali ia naik, ia menjadi lantai baru. Gajimu bisa turun, lantai itu tidak ikut turun."),
  ("titulo", "Kontrak sewa", "tidak peduli bonusmu batal",
   "Kontrak sewa tidak peduli bonusmu batal. Sekolah tidak menurunkan biaya karena lemburmu dihapus. Lantai itu keras."),
  ("item", "Karena itu", "hitung ulang saat naik, bukan saat susah",
   "Karena itu waktu paling penting untuk menghitung ulang anggaran bukan saat kamu sedang kesulitan. Waktunya justru di bulan gajimu naik, ketika semuanya terasa longgar."),
  ("titulo", "Dan di atas lantai baru itu", "duduk satu angka lagi",
   "Dan di atas lantai baru itu duduk satu angka yang jarang sekali masuk hitungan orang:"),
 ]),
 ("Bunga yang memakan sisanya", [
  ("titulo", "Suku bunga acuan", "lima koma tujuh lima persen",
   "Suku bunga acuan bank sentral berada di lima koma tujuh lima persen, setelah dinaikkan dua puluh lima basis poin dalam pertemuan terakhirnya."),
  ("item", "Alasannya", "menahan laju inflasi",
   "Alasannya menahan laju inflasi, karena angka tahunan sudah melewati batas atas sasaran yang ditetapkan. Itu tugas yang memang ada di tangan mereka."),
  ("titulo", "Bagi bank sentral", "itu obat",
   "Bagi bank sentral, menaikkan bunga adalah obat. Bagi orang yang punya cicilan berjalan, obat itu punya harga yang dibayar bulanan."),
  ("item", "Bunga acuan naik", "biaya meminjam naik",
   "Ketika suku bunga acuan naik, biaya meminjam ikut naik di seluruh sistem. Cicilan rumah dengan bunga mengambang menyesuaikan, dan pembiayaan kendaraan baru dihitung ulang."),
  ("titulo", "Sekarang perhatikan", "urutan waktunya",
   "Sekarang perhatikan urutan waktunya, karena di situ letak persoalannya. Kenaikan gajimu ditetapkan satu kali, di akhir tahun sebelumnya, lalu dikunci selama dua belas bulan."),
  ("item", "Suku bunga", "bisa bergerak beberapa kali setahun",
   "Suku bunga acuan ditinjau setiap bulan dan bisa bergerak beberapa kali di dalam tahun yang sama, mengikuti kondisi yang berubah."),
  ("titulo", "Jadi satu sisi neracamu", "beku",
   "Jadi satu sisi neracamu dibekukan selama setahun penuh, sementara sisi lainnya tetap bebas bergerak. Kamu masuk ke tahun itu dengan angka yang sudah ditetapkan sebelum kondisinya diketahui."),
  ("item", "Kamu tidak kalah", "kamu terlambat",
   "Kamu tidak sedang kalah bersaing dengan siapa pun. Kamu sedang terlambat secara struktural, sepanjang tahun, karena memang begitu jadwalnya disusun."),
  ("titulo", "Ini juga menjelaskan", "kenapa utang terasa berbeda",
   "Ini juga menjelaskan kenapa utang terasa berbeda sekarang dibanding beberapa tahun lalu, meskipun jumlah pinjamanmu sama persis."),
  ("item", "Cicilan yang dulu ringan", "bisa jadi berat tanpa kamu menambah apa pun",
   "Cicilan yang dulu terasa ringan bisa menjadi berat tanpa kamu menambah pinjaman sama sekali. Yang berubah bukan utangmu, melainkan harga uang itu sendiri."),
  ("titulo", "Sampai titik ini", "kebanyakan orang masih bertahan",
   "Sampai titik ini kebanyakan orang masih bertahan. Yang berubah pada mereka bukan angka di rekening, melainkan sesuatu yang jauh lebih sulit dilihat:"),
 ]),
 ("Yang menyusut lebih dulu", [
  ("titulo", "Ketika ruang menyempit", "pemotongan punya urutan",
   "Ketika ruang di anggaran menyempit, pemotongan tidak terjadi secara acak. Ada urutannya, urutan itu sama di banyak rumah tangga, dan yang menarik, urutan itu tercatat dalam data."),
  ("barras", "Porsi pengeluaran", ["Hiburan 2019", "Hiburan 2024", "Kendaraan 2019", "Kendaraan 2024"], [47, 38, 90, 64],
   "Porsi pengeluaran untuk hiburan turun dari nol koma empat tujuh persen menjadi nol koma tiga delapan persen dalam lima tahun."),
  ("item", "Kendaraan", "dari lima koma enam tiga ke tiga koma sembilan sembilan",
   "Porsi untuk kendaraan turun jauh lebih tajam, dari lima koma enam tiga persen menjadi tiga koma sembilan sembilan persen dalam periode yang sama."),
  ("titulo", "Angkanya terlihat kecil", "artinya tidak kecil",
   "Angka-angka itu terlihat kecil kalau dibaca sebagai persen. Artinya sama sekali tidak kecil, karena yang sedang kamu lihat adalah jutaan keputusan yang diambil ke arah yang sama."),
  ("item", "Yang dipotong duluan", "yang paling mudah ditunda",
   "Dan yang dipotong lebih dulu selalu yang paling mudah ditunda. Bukan yang paling tidak penting. Dua hal itu sering kali bukan hal yang sama."),
  ("lista", "Yang biasanya ditunda", ["Liburan", "Ganti kendaraan", "Kelas dan pelatihan"],
   "Liburan ditunda ke tahun depan. Ganti kendaraan ditunda sampai yang lama benar-benar berhenti. Kelas dan pelatihan ditunda sampai keadaan membaik."),
  ("titulo", "Dua yang pertama", "memang bisa menunggu",
   "Dua yang pertama memang bisa menunggu, dan menundanya tidak melukai siapa pun. Liburan yang ditunda tetap bisa terjadi tahun depan."),
  ("item", "Yang ketiga", "adalah penghasilanmu tiga tahun lagi",
   "Yang ketiga bukan hiburan yang tertunda. Yang ketiga adalah penghasilanmu tiga tahun lagi, dipotong hari ini, tanpa terlihat sebagai pemotongan."),
  ("titulo", "Ia tidak muncul", "sebagai kerugian",
   "Ia tidak pernah muncul sebagai kerugian di catatan mana pun, karena kerugiannya berupa sesuatu yang tidak jadi terjadi."),
  ("titulo", "Di situ lingkarannya", "menutup",
   "Di situ lingkarannya menutup. Tekanan hari ini memotong justru hal yang seharusnya mengangkatmu keluar dari tekanan itu."),
  ("item", "Dan begitu terpotong", "tekanan tahun depan lebih besar",
   "Dan begitu hal itu terpotong, tekanan tahun depan menjadi sedikit lebih besar, yang membuat pemotongan berikutnya terasa lebih masuk akal lagi."),
  ("item", "Lingkaran ini", "punya jejak nasional",
   "Lingkaran ini bukan cerita satu rumah tangga yang sedang sial. Ia meninggalkan jejak yang cukup besar untuk dihitung:"),
 ]),
 ("Angka yang sebenarnya", [
  ("barras", "Jumlah kelas menengah", ["2019", "2024", "2025"], [100, 83, 81],
   "Jumlah kelas menengah tercatat lima puluh tujuh koma tiga tiga juta orang pada dua ribu sembilan belas."),
  ("item", "Lima tahun kemudian", "empat puluh tujuh koma delapan lima juta",
   "Lima tahun kemudian angkanya empat puluh tujuh koma delapan lima juta orang."),
  ("item", "Setahun setelahnya", "empat puluh enam koma tujuh juta",
   "Setahun setelahnya, empat puluh enam koma tujuh juta. Penurunannya belum berhenti."),
  ("titulo", "Sekitar sepuluh juta orang", "berpindah posisi",
   "Sekitar sepuluh juta orang berpindah posisi dalam waktu enam tahun. Itu bukan angka statistik yang jauh, itu jumlah penduduk beberapa kota besar sekaligus."),
  ("titulo", "Dan ini bagian pentingnya", "mereka tetap bekerja",
   "Dan ini bagian pentingnya. Sebagian besar dari mereka tidak kehilangan pekerjaan. Mereka tetap bekerja, dan gaji mereka juga naik setiap tahun, mengikuti rumus yang sama."),
  ("titulo", "Itu poinnya", "dan poin ini tidak nyaman",
   "Itulah poin yang tidak nyaman untuk diterima. Gaji naik tidak menjamin apa pun, kalau yang naik lebih cepat justru hal-hal yang tidak kamu pilih."),
  ("titulo", "Ini bukan alasan menyerah", "dan bukan alasan menyalahkan diri",
   "Ini bukan alasan untuk menyerah, dan juga bukan alasan untuk terus menyalahkan diri sendiri. Ini alasan untuk berhenti mengukur diri dengan alat ukur yang salah."),
  ("titulo", "Jadi apa yang bisa dilakukan", "tanpa janji kosong",
   "Jadi apa yang benar-benar bisa dilakukan, tanpa menjanjikan hal yang tidak bisa dijanjikan siapa pun?"),
  ("lista", "Tiga langkah", ["Hitung ulang saat gaji naik", "Kunci satu pos", "Jaga pos yang mengangkat"],
   "Tiga langkah, dan ketiganya bisa kamu ukur hasilnya bulan depan, bukan bertahun-tahun lagi."),
  ("item", "Pertama", "hitung ulang di bulan gajimu naik",
   "Pertama, hitung ulang persis di bulan gajimu naik. Bukan tiga bulan setelahnya, karena lantai baru itu terbentuk dalam tiga puluh hari pertama, saat semuanya masih terasa longgar."),
  ("item", "Kedua", "kunci satu pos yang menempel",
   "Kedua, pilih satu pos yang menempel pada penghasilan, dan kunci nilainya di angka lama selama enam bulan. Satu pos saja, bukan semuanya, karena yang mencoba mengunci semuanya biasanya berhenti di minggu ketiga."),
  ("item", "Selisihnya", "pindahkan sebelum kamu melihatnya",
   "Selisih yang muncul dari satu pos itu dipindahkan otomatis di hari gajian, sebelum sempat kamu lihat sebagai uang yang tersedia."),
  ("item", "Ketiga", "jaga pos yang mengangkat penghasilanmu",
   "Ketiga, jangan potong pos yang mengangkat penghasilanmu nanti, meskipun itu pos yang paling mudah dipotong dan paling tidak menimbulkan keributan di rumah."),
  ("titulo", "Tiga langkah ini", "tidak mengubah rumusnya",
   "Tiga langkah ini tidak mengubah rumus kenaikan upah, tidak menurunkan suku bunga, dan tidak membuat harga bahan bakar berhenti bergerak."),
  ("item", "Yang berubah", "jarak antara dua angka",
   "Yang berubah adalah jarak antara kenaikan yang tercatat di slipmu dan kenaikan yang benar-benar kamu rasakan di minggu ketiga."),
  ("cta", "Bagian mana", "yang paling terasa di bulanmu",
   "Dari lima bagian tadi, mana yang paling terasa di bulanmu? Tulis di kolom komentar, karena angka setiap orang berbeda, dan bagian itu justru yang paling berguna dibaca bersama-sama."),
 ]),
]
